"""Generate 48x48 monochrome XBM navigation assets from simple SVG geometry."""
from pathlib import Path
import re
import xml.etree.ElementTree as ET

try:
    ROOT = Path(__file__).resolve().parents[1]
except NameError:
    Import("env")
    ROOT = Path(env["PROJECT_DIR"])

SOURCE = ROOT / "assets" / "icons"
OUTPUT = ROOT / "src" / "ui" / "navigation_icons.h"

SIZE = 48
STROKE = 4

NAMES = [
    "straight", "left", "right", "slight_left", "slight_right", "sharp_left",
    "sharp_right", "uturn_left", "uturn_right", "roundabout", "destination",
    "merge", "exit", "keep_left", "keep_right",
]
ENUMS = [
    "Straight", "Left", "Right", "SlightLeft", "SlightRight", "SharpLeft",
    "SharpRight", "UTurnLeft", "UTurnRight", "Roundabout", "Destination",
    "Merge", "Exit", "KeepLeft", "KeepRight",
]

def point(canvas, x, y):
    radius = STROKE // 2
    for yy in range(y - radius, y + radius + 1):
        for xx in range(x - radius, x + radius + 1):
            if 0 <= xx < SIZE and 0 <= yy < SIZE and (xx-x)**2 + (yy-y)**2 <= radius**2 + 1:
                canvas[yy][xx] = 1

def line(canvas, a, b):
    x0, y0 = a; x1, y1 = b
    dx, dy = abs(x1-x0), -abs(y1-y0)
    sx, sy = (1 if x0 < x1 else -1), (1 if y0 < y1 else -1)
    error = dx + dy
    while True:
        point(canvas, x0, y0)
        if (x0, y0) == (x1, y1): break
        twice = 2 * error
        if twice >= dy: error += dy; x0 += sx
        if twice <= dx: error += dx; y0 += sy

def render(path):
    canvas = [[0] * SIZE for _ in range(SIZE)]
    root = ET.parse(path).getroot()
    for node in root.iter():
        tag = node.tag.rsplit("}", 1)[-1]
        if tag in ("polyline", "polygon"):
            nums = [float(v) for v in re.findall(r"-?\d+(?:\.\d+)?", node.get("points", ""))]
            pts = [(round(nums[i]), round(nums[i+1])) for i in range(0, len(nums)-1, 2)]
            if tag == "polygon" and pts: pts.append(pts[0])
            for a, b in zip(pts, pts[1:]): line(canvas, a, b)
        elif tag == "line":
            line(canvas, (round(float(node.get("x1"))), round(float(node.get("y1")))),
                 (round(float(node.get("x2"))), round(float(node.get("y2")))))
        elif tag == "circle":
            cx, cy, radius = (float(node.get(k)) for k in ("cx", "cy", "r"))
            previous = None
            for degree in range(0, 361, 5):
                import math
                current = (round(cx + radius * math.cos(math.radians(degree))),
                           round(cy + radius * math.sin(math.radians(degree))))
                if previous: line(canvas, previous, current)
                previous = current
    packed = []
    for y in range(SIZE):
        for x in range(0, SIZE, 8):
            packed.append(sum(canvas[y][x+bit] << bit for bit in range(8)))
    return packed

def generate():
    output = ["#pragma once", "// Generated by tools/generate_icons.py. Do not edit.",
              "#include <Arduino.h>", "#include \"services/iphone_service.h\"", "namespace NavigationIcons {"]
    for name in NAMES:
        values = render(SOURCE / f"{name}.svg")
        output.append(f"const uint8_t {name}[] PROGMEM = {{")
        for offset in range(0, len(values), 16):
            output.append("    " + ", ".join(f"0x{x:02x}" for x in values[offset:offset+16]) + ",")
        output.append("};")
    output.append("inline const uint8_t* get(Maneuver value) { switch (value) {")
    for enum, name in zip(ENUMS, NAMES): output.append(f"case Maneuver::{enum}: return {name};")
    output.extend(["} return straight; }", "}", ""])
    OUTPUT.write_text("\n".join(output), encoding="utf-8")

generate()
